config/routes.rb
Rails.application.routes.draw do
  resources :questions do
  resources :answers
  end
  resources :answers, only: [:update]
  root to: 'visitors#index'
end

app/models/answer.rb
class Answer < ActiveRecord::Base
  belongs_to :question

  validates :body, length: { minimum: 50 }, presence: true
end

app/models/question.rb
class Question < ActiveRecord::Base
  has_many :answers, dependent: :destroy

  validates :title, length: { maximum: 40 }, presence: true
  validates :description, length: { maximum: 150 }, presence: true
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController

  def index
    @question = Question.find(params[:question_id])
    @answers = @question.answers
  end

  def new
    @question = Question.find(params[:question_id])
    @answer = Answer.new
  end

  def update
    @best_answer = Answer.find(params[:id])
    @question = @best_answer.question
    @answer = Answer.new
    @answers = @question.answers

    @best_answer.best_answer = true
    @best_answer.save
    redirect_to question_path(@question)
  end

  def create
    @question = Question.find(params[:question_id])
    @answer = Answer.new(answer_params)
    @answer.question = @question

    if @answer.save
      flash[:notice] = "Answer saved successfully."
      redirect_to question_path(@question)
    else
      flash[:alert] = "Failed to save answer."
      render :new
    end
  end

  def answer_params
    params.require(:answer).permit(:body)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController

  def index
    @questions = Question.all.order("id desc").limit(5)
  end

  def show
    @question = Question.find(params[:id])
    @answers = @question.answers.order(best_answer: :desc)
  end

  def edit
    @question = Question.find(params[:id])
  end

  def new
    @question = Question.new
  end

  def create
    @question = Question.new(question_params)
    if @question.save
      redirect_to questions_path
    else
      render :new
    end
  end

  def destroy
    @question = Question.find(params[:id])
    @answers = @question.answers
    if @question.destroy
      @answers.destroy
      redirect_to questions_path
    end
  end

  def update
    @question = Question.find(params[:id])
    if @question.update(question_params)
       redirect_to questions_path
     else
       render :edit
     end
  end

  private

    def set_question
      @question = Question.find(params[:id])
    end

    def question_params
      params.require(:question).permit(:title, :description)
    end
end

app/controllers/visitors_controller.rb
class VisitorsController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
  def markdown(text)
    options = {
      filter_html:     true,
      hard_wrap:       true,
      link_attributes: { rel: 'nofollow', target: "_blank" },
      space_after_headers: true,
      fenced_code_blocks: true
    }

    extensions = {
      autolink:           true,
      superscript:        true,
      disable_indented_code_blocks: true
    }

    renderer = Redcarpet::Render::HTML.new(options)
    markdown = Redcarpet::Markdown.new(renderer, extensions)

    markdown.render(text).html_safe
  end
end

app/views/answer/_form.html.erb
<%= form_for @answer, url: { action: 'create'}, html: {class: 'f-this'} do |f| %>
  <% if @answer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@answer.errors.count, "error") %> prohibited this answer from being saved:</h2>

      <ul>
      <% @answer.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label : %>:<br>
    <%= f.text_field :title %>
  </div>

app/views/answers/_form.html.erb
<%= form_for @answer, url: { action: 'create'}, html: {class: 'f-this'} do |f| %>
  <% if @answer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@answer.errors.count, "error") %> prohibited this answer from being saved:</h2>

      <ul>
      <% @answer.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= f.text_area :body %>
  </div>

  <div class="actions">
    <%= f.submit class: "button" %>
  </div>
<% end %>

app/views/answers/new.html.erb
<info>
  <h1>Rescue<strong> Mission</strong></h1>
  <p>write your best Answer</p>
</info>

<div class="page">
  <strong>Title</strong>
    <%= markdown(@question.title) %>
  <br>
  <strong>Description</strong>
    <%= markdown(@question.description) %>

<h1>New Answer</h1>
  <%= render 'form' %>
</div>

<%= link_to 'Back', root_path %>

app/views/answers/show.html.erb
<p>
  <strong>Title:</strong>
  <%= @question.title %>
  <br>
  <strong>Description:</strong>
  <%= @question.description %>
</p>


<h1>New Answer</h1>
  <%= render 'form' %>
  <%= link_to 'Back', root_path %>

app/views/layouts/_nav_bar.html.erb
<input id="nav-toggle" type="checkbox" name="nav-toggle" class="nav-toggle"/><a id="body-overlay" href="#"></a>
<aside id="side-nav">
  <nav id="mobile-nav">
    <ul>
      <li class="active"><a href="#">Questions</a></li>
      <li><a href="/questions">All</a></li>
      <li><a href="/questions/new">New</a></li>
    </ul>
  </nav>
</aside>
<div id="wrapper">
  <header>
    <div id="header-inner">
      <label for="nav-toggle" class="mobile-toggle">
        <div class="top-bar"></div>
        <div class="middle-bar"></div>
        <div class="bottom-bar"></div>
      </label>
    </div>
  </header>
  <main>
    <info>
      <h1>Rescue<strong> Mission</strong></h1>
      <p>write your best Question</p>
    </info>
    <section class="page">
      <h2>Question of the Day</h2>
      <% @question = Question.all.sample%>
      <p> <%= link_to (@question.title), question_path(@question.id) %> </p>
      <p> <%= @question.description %> </p>
    </section>
  </main>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "Untitled" %></title>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "application", 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>

  <body>
    
    <%= yield %>

  </body>
</html>

app/views/questions/_form.html.erb
<%= form_for @question do |f| %>
  <% if @question.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@question.errors.count, "error") %> prohibited this question from being saved:</h2>

      <ul>
      <% @question.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <info>
    <h1>Rescue<strong> Mission</strong></h1>
    <p>write your best Question</p>
  </info>

  <div class="page">
    <div class="field">
    <h1><%= f.label :title %></h1>
        <%= f.text_field :title %>
    </div>

    <div class="field">
    <h1><%= f.label :description %></h1>
      <%= f.text_area :description %>
    </div>

    <div class="actions">
      <%= f.submit class: "button"%>
    </div>
  </div>
<% end %>

app/views/questions/edit.html.erb
<h1>Editing Question</h1>

<%= render 'form' %>

<%= link_to 'Show', @question %> |
<%= link_to 'Back', questions_path %>

app/views/questions/index.html.erb
<div class="page">
  <info>
    <h1>Rescue<strong> Mission</strong></h1>
    <p>List of Questions</p>
  </info>
  <table>
    <thead>
      <tr>
        <th>Name</th>
        <th colspan="3"></th>
      </tr>
    </thead>
    <tbody>
      <% @questions.each do |question| %>
        <tr>
          <td><%= question.title %></td>
          <td><%= link_to 'Show', question %></td>
          <td><%= link_to 'Edit', edit_question_path(question) %></td>
          <td><%= link_to 'Destroy', question, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>
<br>
<%= link_to 'New Question', new_question_path, class: "button" %>
<%= link_to 'Back', root_path %>

app/views/questions/new.html.erb
<%= render 'form' %>
<%= link_to 'Back', root_path %>

app/views/questions/show.html.erb
<p id="notice"><%= notice %></p>

<info>
  <h1>Rescue<strong> Mission</strong></h1>
  <p>write your best Question</p>
</info>

<section class="page">
  <h1><%= markdown(@question.title) %></h1>
        <strong>Description:</strong>
        <%= markdown(@question.description) %>
</section>

  <div class="row">
    <div class="page">
      <h1>Answers</h1>
      <% @answers.each do |answer| %>
      <% if answer.best_answer == true %>
        <h4>Best</h4>
      <% end %>
        <%= markdown(answer.body) %> - <%= link_to 'Best Answer?', answer_path(answer), method: :put, class: "button" %>
      <% end %>
    </div>
  </div>

<%= link_to 'Answer',new_question_answer_path(@question), class: "button" %>
<%= link_to 'Back', root_path, class: "button"%>

app/views/visitors/index.html.erb
<header>
 <%= render 'layouts/nav_bar' %>
</header>